oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp
#            enable_progress: true
            storage:
                type: gaufrette
                filesystem: gaufrette.gallery_filesystem 
            enable_cancelation: true